//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.InventoryDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventoryDAL : DbContext
    {
        public InventoryDAL()
            : base("name=InventoryDAL")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OtherProperty> OtherProperty { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<PhotoList> PhotoList { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<UserInfoShop> UserInfoShop { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<CheckType> CheckType { get; set; }
        public virtual DbSet<AnswerPhoto> AnswerPhoto { get; set; }
        public virtual DbSet<Answer> Answer { get; set; }
    }
}
