//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.yrtech.InventoryDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remark
    {
        public int RemarkId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> CheckTypeId { get; set; }
        public string RemarkName { get; set; }
        public string AddCheck { get; set; }
        public Nullable<bool> UseChk { get; set; }
        public string InUserId { get; set; }
        public Nullable<System.DateTime> InDateTime { get; set; }
        public string ModifyUserId { get; set; }
        public Nullable<System.DateTime> ModifyDateTime { get; set; }
    }
}
